### ISSUE TITLE
Any command line arguments needed?

### ISSUE THREAD

**Issue by F08H15** [ddemidov/amgcl_benchmarks#5]
Dear AMGCL developers, I am trying to get to grips with the shared memory version of the benchmarks, with a particular interest in the Navier-Stokes test. As I did not find any other information, I always launch the executables without any further command line option (the matrix and the rhs are in the same directory as the executables).
smem_ns_amgcl returns after 198 iterations with an error < 1e-4.
smem_ns_amgcl_scalar needs 201 iterations and finishes likewise with an error < 1e-4.
However, smem_ns_schur (which I expected to perform better than the two previous ones), stops after 100 iterations and has not converged yet (error = 3e-3).
Am I missing anything? Any command line options?

**Comment by ddemidov** [comment]
The executables do not take any command-line options besides the matrix and the RHS file names, but the benchmarks are quite old. Schur pressure correction preconditioner has been updated many times since then, so some of the defaults could have been changed. I would suggest looking at [1] and the corresponding code [2] for more recent examples of solving Navier-Stokes problems with amgcl.

[1] Demidov, Denis, Lin Mu, and Bin Wang. "Accelerating linear solvers for Stokes problems with C++ metaprogramming." Journal of Computational Science 49 (2021): 101285. https://arxiv.org/abs/2006.06052
[2] https://github.com/ddemidov/cppstokes_benchmarks

**Comment by F08H15** [comment]
Thank you very much. I'll give it a try with the more recent sources.
